######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 23:08:54 2014
######################################################################

TEMPLATE = app
TARGET = miner-cpu
INCLUDEPATH += .
QT += network

# Input
HEADERS += sha256sum.h
SOURCES += main.cpp sha256sum.c
