######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 23:08:54 2014
######################################################################

TEMPLATE = app
TARGET = miner-cpu
INCLUDEPATH += .
QT += network
CONFIG += c++11

# Input
HEADERS += sha256sum.h Sha256.h
SOURCES += main.cpp sha256sum.c Sha256.cpp
